### PR TITLE
Feature/tests

### PR DESCRIPTION
**Pull request by MrTimeey**
Hi @FotieMConstant 
Today I wanted to learn something about tests and though it could be a great idea to add some to your api.
Hope you like it!

### CODE REVIEW

**Comment by MrTimeey** [comment]
Side note:
I also build a little vue-application which consumes your api

- https://mrtimeey.github.io/geek-quotes-app/
- https://github.com/MrTimeey/geek-quotes-app 

Would be happy to hear your feedback :)

**Review by FotieMConstant — APPROVED** [review]
Hi, @MrTimeey Thanks for this amazing PR. I can see you added some conditions on the keyword endpoints, I actually love the idea. and for the test. It's nice to have those, though I've never really written any test in moha. Worked more with Jasmine... Everything looks good.

**Comment by FotieMConstant** [comment]
> Side note:
> I also build a little vue-application which consumes your api
> 
> * https://mrtimeey.github.io/geek-quotes-app/
> * https://github.com/MrTimeey/geek-quotes-app
> 
> Would be happy to hear your feedback :)

...and for this, it's really amazing. I love it... @quiet-programmer is working on an app version which he said will publish on play store when done. You guys can work on a similar design. Will see, if I get some time I might add some stuff... hope you welcome PRs.

**Comment by sudo-which-qp** [comment]
The site is nice really nice... I think there should be like a button that says "Random Quotes" or a Button with a refresh Icon... but the design is great

**Review by sudo-which-qp — COMMENTED** [review]
Nice Bro.... started learning Node like last month... this I pretty nice

**Review by sudo-which-qp — COMMENTED** [review]
this is good tho.... was about doing this... but was really busy

**Comment by MrTimeey** [comment]
@FotieMConstant thank you 😊 and pull requests are always welcome 🎉😊
@quiet-programmer i've added a refresh on click on the app title. Currently I'm thinking about how to include the buttons 😊 maybe I will include them later this evening

**Comment by FotieMConstant** [comment]
Awesome, so @quiet-programmer when are we getting an android version? lol!

**Comment by sudo-which-qp** [comment]
Very soon.... just wanna add something to it

**Comment by MrTimeey** [comment]
Just updated the app with a reload butto :)

**Comment by MrTimeey** [comment]
@FotieMConstant can you change the readme to my Github username 'MrTimeey'? I don't know why but i think it looks nicer in this context 🤣

**Comment by FotieMConstant** [comment]
> @FotieMConstant can you change the readme to my Github username 'MrTimeey'? I don't know why but i think it looks nicer in this context 🤣

Sure

**Pull request merged**
