### PR TITLE
Adding features

### PR DESCRIPTION
**Pull request by sudo-which-qp**
Added a middleware for 404 requests, to display an HTML file for 404 request

### CODE REVIEW

**Review by FotieMConstant — APPROVED** [review]
Hi @quiet-programmer, Thanks for your PR. You've added some awesome features there man. big up!

**Review by FotieMConstant — APPROVED** [review]
Thanks for this PR. I was actually looking to separate the quotes from the actual server code. You literally saved my life man... Nice job!

**Comment by FotieMConstant** [comment]
Hey, @quiet-programmer, When you are ready, I can merge your branch to main. Just let me know man.

**Comment by sudo-which-qp** [comment]
> Hey, @quiet-programmer, When you are ready, I can merge your branch to main. Just let me know man.

kinda having issues now sending a pull request... don't know if it has been sent or not

**Comment by sudo-which-qp** [comment]
> > Hey, @quiet-programmer, When you are ready, I can merge your branch to main. Just let me know man.
> 
> kinda having issues now sending a pull request... don't know if it has been sent or not



> Hey, @quiet-programmer, When you are ready, I can merge your branch to main. Just let me know man.

you can merge it man... I don't have access to merge it here... Thanks for approving Man

**Pull request merged**
